Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  
  #provisioning
  config.vm.provision :shell, path: "provision/core.sh"
  config.vm.provision :shell, path: "provision/vagrant.sh"

  # Enable USB Controller on VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
end

