# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.box = "cristianchaparroa/kali-netinstall"
  config.vm.box_version = "2022.2"

  #provisioning
  config.vm.provision :shell, path: "provision/core.sh"
  config.vm.provision :shell, path: "provision/adapters/alfa_awus036ach.sh"


  if Vagrant.has_plugin?("vagrant-vbguest") then
          config.vbguest.auto_update = false
  end

  # Its required to install on host system the virtualbox extension pack
  #
  # Enable USB Controller on VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
  
end
